default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: albums_app_development

test:
  <<: *default
  database: albums_app_test

production:
  <<: *default
  database: albums_app_production
  username: albums_app
  password: <%= ENV['ALBUMS_APP_DATABASE_PASSWORD'] %>
